all:
  children:
    windows:
      hosts:
        local_iis:
          ansible_host: 172.28.51.148
          ansible_connection: winrm
          ansible_port: 5985
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_user: "{{ lookup('env', 'ANSIBLE_REMOTE_USER') }}"
          ansible_password: "{{ lookup('env', 'ANSIBLE_REMOTE_PASSWORD') }}"